name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run credo with reviewdog
      uses: red-shirts/reviewdog-action-credo@v1
      with:
        github_token: ${{ secrets.github_token }}
